<?php

/**
 * @file
 * Installation functions for node to json module.
 */

/**
 * Implements hook_install().
 */
function node_to_json_install() {
  $path = "public://json";
  if (file_prepare_directory($path, FILE_CREATE_DIRECTORY)){
    drupal_set_message(t("Default folder was be created"), 'status');
  }else{
    drupal_set_message(t("it was not possible to create the directory"), 'error');
  }
}
